resource_path: ["../"]
bibliography: bibliography.bib
citestyle: ieee.csl
reference-location: margin
toc: true
execute:
  freeze: auto
# filters:
#   - include-code-files

project:
  type: website
  output-dir: "docs"
  render:
    - course/index.md
    - course/theory-1-introduction.md
    - course/theory-1-motivating-example-ode.ipynb
    - course/practical-1-setup.md
    - course/motivating-example.ipynb
    - course/theory-2-regression.md
    - course/practical-2-bambi.qmd
    - course/theory-3-mcmc.qmd
    - course/practical-3-stack.qmd
    - course/practical-4-jax.qmd
    - course/theory-4-diagnostics.qmd
    - course/practical-5-diagnostics.qmd
    - course/theory-5-odes.md
    - course/practical-6-odes.

website:
  title: "Bayesian Statistics for Computational Biology"
  navbar:
    tools:
      - icon: github
        url:  https://github.com/dtu-qmcm/bayesian_statistics_for_computational_biology
  sidebar:
    style: "docked"
    serach: true
    contents:
      - section: "Admin"
        contents:
        - course/index.md
      - section: "Theory"
        contents:
        - course/theory-1-introduction.md
        - course/theory-1-motivating-example-ode.ipynb
        - course/theory-2-regression.md
        - course/theory-3-mcmc.qmd
        - course/theory-4-diagnostics.qmd
        - course/theory-5-odes.md
      - section: "Practical"
        contents:
        - course/practical-1-setup.md
        - course/practical-2-bambi.qmd
        - course/practical-3-stack.qmd
        - course/practical-4-jax.qmd
        - course/practical-5-diagnostics.qmd
        - course/practical-6-odes.qmd

format:
  html:
    theme: cosmo
    embed-resources: true
    include-in-header: mathjax.html
  ipynb: default
