resource_path: ["../"]
bibliography: bibliography.bib
citestyle: ieee.csl
reference-location: margin
toc: true
execute:
  freeze: auto
# filters:
#   - include-code-files

project:
  type: website
  output-dir: "docs"
  render:
    - course_materials/index.md
    - course_materials/day-1-am-introduction.md
    - course_materials/day-1-am-motivating-example.ipynb
    - course_materials/day-1-pm-setup.md
    - course_materials/day-2-am-regression.md
    - course_materials/day-2-pm-bambi.qmd
    - course_materials/day-3-am-mcmc.qmd
    - course_materials/day-3-pm-stack.qmd

website:
  title: "Bayesian Statistics for Computational Biology"
  navbar:
    tools:
      - icon: github
        url:  https://github.com/biosustain/bayesian_statistics_for_computational_biology
  sidebar:
    style: "docked"
    serach: true
    contents:
      - section: "Admin"
        contents:
        - course_materials/index.md
      - section: "Course materials"
        contents:
        - course_materials/day-1-am-introduction.md
        - course_materials/day-1-am-motivating-example.ipynb
        - course_materials/day-1-pm-setup.md
        - course_materials/day-2-am-regression.md
        - course_materials/day-2-pm-bambi.qmd
        - course_materials/day-3-am-mcmc.qmd
        - course_materials/day-3-pm-stack.qmd

format:
  html:
    theme: cosmo
    embed-resources: true
    include-in-header: mathjax.html
  ipynb: default
